/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const ProfilepageLazyImport = createFileRoute('/profilepage')()
const OversigtLazyImport = createFileRoute('/oversigt')()
const MybookingsLazyImport = createFileRoute('/mybookings')()
const MedialabLazyImport = createFileRoute('/medialab')()
const MakerlabLazyImport = createFileRoute('/makerlab')()
const LoginLazyImport = createFileRoute('/login')()
const ForgotpasswordLazyImport = createFileRoute('/forgotpassword')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const ChangepasswordLazyImport = createFileRoute('/changepassword')()
const BooklokaleLazyImport = createFileRoute('/booklokale')()
const AuditoriumLazyImport = createFileRoute('/auditorium')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const ProfilepageLazyRoute = ProfilepageLazyImport.update({
  id: '/profilepage',
  path: '/profilepage',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profilepage.lazy').then((d) => d.Route))

const OversigtLazyRoute = OversigtLazyImport.update({
  id: '/oversigt',
  path: '/oversigt',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/oversigt.lazy').then((d) => d.Route))

const MybookingsLazyRoute = MybookingsLazyImport.update({
  id: '/mybookings',
  path: '/mybookings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mybookings.lazy').then((d) => d.Route))

const MedialabLazyRoute = MedialabLazyImport.update({
  id: '/medialab',
  path: '/medialab',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/medialab.lazy').then((d) => d.Route))

const MakerlabLazyRoute = MakerlabLazyImport.update({
  id: '/makerlab',
  path: '/makerlab',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/makerlab.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const ForgotpasswordLazyRoute = ForgotpasswordLazyImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgotpassword.lazy').then((d) => d.Route),
)

const DashboardLazyRoute = DashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const ChangepasswordLazyRoute = ChangepasswordLazyImport.update({
  id: '/changepassword',
  path: '/changepassword',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/changepassword.lazy').then((d) => d.Route),
)

const BooklokaleLazyRoute = BooklokaleLazyImport.update({
  id: '/booklokale',
  path: '/booklokale',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/booklokale.lazy').then((d) => d.Route))

const AuditoriumLazyRoute = AuditoriumLazyImport.update({
  id: '/auditorium',
  path: '/auditorium',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auditorium.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auditorium': {
      id: '/auditorium'
      path: '/auditorium'
      fullPath: '/auditorium'
      preLoaderRoute: typeof AuditoriumLazyImport
      parentRoute: typeof rootRoute
    }
    '/booklokale': {
      id: '/booklokale'
      path: '/booklokale'
      fullPath: '/booklokale'
      preLoaderRoute: typeof BooklokaleLazyImport
      parentRoute: typeof rootRoute
    }
    '/changepassword': {
      id: '/changepassword'
      path: '/changepassword'
      fullPath: '/changepassword'
      preLoaderRoute: typeof ChangepasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/forgotpassword': {
      id: '/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof ForgotpasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/makerlab': {
      id: '/makerlab'
      path: '/makerlab'
      fullPath: '/makerlab'
      preLoaderRoute: typeof MakerlabLazyImport
      parentRoute: typeof rootRoute
    }
    '/medialab': {
      id: '/medialab'
      path: '/medialab'
      fullPath: '/medialab'
      preLoaderRoute: typeof MedialabLazyImport
      parentRoute: typeof rootRoute
    }
    '/mybookings': {
      id: '/mybookings'
      path: '/mybookings'
      fullPath: '/mybookings'
      preLoaderRoute: typeof MybookingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/oversigt': {
      id: '/oversigt'
      path: '/oversigt'
      fullPath: '/oversigt'
      preLoaderRoute: typeof OversigtLazyImport
      parentRoute: typeof rootRoute
    }
    '/profilepage': {
      id: '/profilepage'
      path: '/profilepage'
      fullPath: '/profilepage'
      preLoaderRoute: typeof ProfilepageLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auditorium': typeof AuditoriumLazyRoute
  '/booklokale': typeof BooklokaleLazyRoute
  '/changepassword': typeof ChangepasswordLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/forgotpassword': typeof ForgotpasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/makerlab': typeof MakerlabLazyRoute
  '/medialab': typeof MedialabLazyRoute
  '/mybookings': typeof MybookingsLazyRoute
  '/oversigt': typeof OversigtLazyRoute
  '/profilepage': typeof ProfilepageLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auditorium': typeof AuditoriumLazyRoute
  '/booklokale': typeof BooklokaleLazyRoute
  '/changepassword': typeof ChangepasswordLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/forgotpassword': typeof ForgotpasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/makerlab': typeof MakerlabLazyRoute
  '/medialab': typeof MedialabLazyRoute
  '/mybookings': typeof MybookingsLazyRoute
  '/oversigt': typeof OversigtLazyRoute
  '/profilepage': typeof ProfilepageLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/auditorium': typeof AuditoriumLazyRoute
  '/booklokale': typeof BooklokaleLazyRoute
  '/changepassword': typeof ChangepasswordLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/forgotpassword': typeof ForgotpasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/makerlab': typeof MakerlabLazyRoute
  '/medialab': typeof MedialabLazyRoute
  '/mybookings': typeof MybookingsLazyRoute
  '/oversigt': typeof OversigtLazyRoute
  '/profilepage': typeof ProfilepageLazyRoute
  '/signup': typeof SignupLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditorium'
    | '/booklokale'
    | '/changepassword'
    | '/dashboard'
    | '/forgotpassword'
    | '/login'
    | '/makerlab'
    | '/medialab'
    | '/mybookings'
    | '/oversigt'
    | '/profilepage'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditorium'
    | '/booklokale'
    | '/changepassword'
    | '/dashboard'
    | '/forgotpassword'
    | '/login'
    | '/makerlab'
    | '/medialab'
    | '/mybookings'
    | '/oversigt'
    | '/profilepage'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/auditorium'
    | '/booklokale'
    | '/changepassword'
    | '/dashboard'
    | '/forgotpassword'
    | '/login'
    | '/makerlab'
    | '/medialab'
    | '/mybookings'
    | '/oversigt'
    | '/profilepage'
    | '/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuditoriumLazyRoute: typeof AuditoriumLazyRoute
  BooklokaleLazyRoute: typeof BooklokaleLazyRoute
  ChangepasswordLazyRoute: typeof ChangepasswordLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  ForgotpasswordLazyRoute: typeof ForgotpasswordLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MakerlabLazyRoute: typeof MakerlabLazyRoute
  MedialabLazyRoute: typeof MedialabLazyRoute
  MybookingsLazyRoute: typeof MybookingsLazyRoute
  OversigtLazyRoute: typeof OversigtLazyRoute
  ProfilepageLazyRoute: typeof ProfilepageLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuditoriumLazyRoute: AuditoriumLazyRoute,
  BooklokaleLazyRoute: BooklokaleLazyRoute,
  ChangepasswordLazyRoute: ChangepasswordLazyRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  ForgotpasswordLazyRoute: ForgotpasswordLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MakerlabLazyRoute: MakerlabLazyRoute,
  MedialabLazyRoute: MedialabLazyRoute,
  MybookingsLazyRoute: MybookingsLazyRoute,
  OversigtLazyRoute: OversigtLazyRoute,
  ProfilepageLazyRoute: ProfilepageLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auditorium",
        "/booklokale",
        "/changepassword",
        "/dashboard",
        "/forgotpassword",
        "/login",
        "/makerlab",
        "/medialab",
        "/mybookings",
        "/oversigt",
        "/profilepage",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/auditorium": {
      "filePath": "auditorium.lazy.jsx"
    },
    "/booklokale": {
      "filePath": "booklokale.lazy.jsx"
    },
    "/changepassword": {
      "filePath": "changepassword.lazy.jsx"
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.jsx"
    },
    "/forgotpassword": {
      "filePath": "forgotpassword.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/makerlab": {
      "filePath": "makerlab.lazy.jsx"
    },
    "/medialab": {
      "filePath": "medialab.lazy.jsx"
    },
    "/mybookings": {
      "filePath": "mybookings.lazy.jsx"
    },
    "/oversigt": {
      "filePath": "oversigt.lazy.jsx"
    },
    "/profilepage": {
      "filePath": "profilepage.lazy.jsx"
    },
    "/signup": {
      "filePath": "signup.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
